export const CREATE_INNOVATION = "CREATE_INNOVATION";
export const RETRIEVE_INNOVATIONS = "RETRIEVE_INNOVATIONS";
export const UPDATE_INNOVATION = "UPDATE_INNOVATION";
export const DELETE_INNOVATION = "DELETE_INNOVATION";


export const CREATE_STARTUP_OPT = "CREATE_STARTUP_OPT";
export const RETRIEVE_STARTUP_OPTS = "RETRIEVE_STARTUP_OPTS";
export const UPDATE_STARTUP_OPT = "UPDATE_STARTUP_OPT";
export const DELETE_STARTUP_OPT = "DELETE_STARTUP_OPT";

export const CREATE_SKILL_OPT = "CREATE_SKILL_OPT";
export const RETRIEVE_SKILL_OPTS = "RETRIEVE_SKILL_OPTS";
export const UPDATE_SKILL_OPT = "UPDATE_SKILL_OPT";
export const DELETE_SKILL_OPT = "DELETE_SKILL_OPT";