export const CREATE_INNOVATION = "CREATE_INNOVATION";
export const RETRIEVE_INNOVATIONS = "RETRIEVE_INNOVATIONS";
export const UPDATE_INNOVATION = "UPDATE_INNOVATION";
export const DELETE_INNOVATION = "DELETE_INNOVATION";
