export const CREATE_INNOVATION = "CREATE_INNOVATION";
export const RETRIEVE_INNOVATIONS = "RETRIEVE_INNOVATIONS";
export const UPDATE_INNOVATION = "UPDATE_INNOVATION";
export const DELETE_INNOVATION = "DELETE_INNOVATION";


export const CREATE_STARTUP_OPT = "CREATE_STARTUP_OPT";
export const RETRIEVE_STARTUP_OPTS = "RETRIEVE_STARTUP_OPTS";
export const UPDATE_STARTUP_OPT = "UPDATE_STARTUP_OPT";
export const DELETE_STARTUP_OPT = "DELETE_STARTUP_OPT";

export const CREATE_SKILL_OPT = "CREATE_SKILL_OPT";
export const RETRIEVE_SKILL_OPTS = "RETRIEVE_SKILL_OPTS";
export const UPDATE_SKILL_OPT = "UPDATE_SKILL_OPT";
export const DELETE_SKILL_OPT = "DELETE_SKILL_OPT";


export const CREATE_EXPERT = "CREATE_EXPERT";
export const RETRIEVE_EXPERTS = "RETRIEVE_EXPERTS";
export const UPDATE_EXPERT = "UPDATE_EXPERT";
export const DELETE_EXPERT = "DELETE_EXPERT";

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';


export const FETCH_ACCOUNTS_SUCCESS = "FETCH_ACCOUNTS_SUCCESS";
export const FETCH_ACCOUNTS_FAILURE = "FETCH_ACCOUNTS_FAILURE";
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const CREATE_ACCOUNT_FAILURE = "CREATE_ACCOUNT_FAILURE";
export const UPDATE_ACCOUNT_SUCCESS = "UPDATE_ACCOUNT_SUCCESS";
export const UPDATE_ACCOUNT_FAILURE = "UPDATE_ACCOUNT_FAILURE";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_FAILURE = "DELETE_ACCOUNT_FAILURE";
