cloud:
  aws:
    credentials:
      access-key: AKIARLZEDVJ7RLCHVFS3
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: howtodobiotech


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB